version: 2
workflows:
  version: 2
  buildAndDeploy:
    jobs:
      - master:
          context: hexlabs-aws
          filters:
            branches:
              only: master
#      - branch:
#          filters:
#            branches:
#              ignore: master

jobs:
  master:
    machine:
      enabled: true
    steps:
      - checkout

      - run:
          name: Install KloudFormation
          command: curl -sSL install.kloudformation.hexlabs.io | bash -s -- -local

#      - restore_cache:
#          keys:
#            - kloudformation-{{ checksum "kloudformation.sh" }}

      - run:
          name: Deploy Bucket Stack
          command:  ./kloudformation.sh -m s3@1.0.11 -v 1.1.136 deploy -stack-name klouds-user-template -stack-class BucketStack -template bucket-stack.yml -output output.properties

      - run:
          name: Deploy and Transpile IAM User Stack
          command:  ./kloudformation.sh -m s3@1.0.11 -v 1.1.136 deploy -stack-class IamStack -stack-name klouds-user -template user-template.yml

      - run:
          name: Upload Template
          command:  ./kloudformation.sh upload -location user-template.yml -bucket klouds-user-template -key template.yml

      - run:
          name: Stack Creation URL
          command: echo https://eu-west-1.console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks/create/review?templateURL=https://klouds-user-template.s3-eu-west-1.amazonaws.com/template.yml&stackName=klouds-user

      - store_artifacts:
          path: user-template.yml
